import { TICKETS_PER_ROW, VIEWPORT_HEIGHT, VIEWPORT_ROWS } from "@/types/ticket";

export const CATALOG_CONFIG = {
  COLUMNS: TICKETS_PER_ROW,
  VISIBLE_ROWS: VIEWPORT_ROWS + 1,
  get CATALOG_MAX_HEIGHT() {
    return VIEWPORT_HEIGHT + 55;
  },
  get VISIBLE_TICKETS_COUNT() {
    return this.COLUMNS * this.VISIBLE_ROWS;
  },
  ANIMATION: {
    NEW_TICKETS_THRESHOLD: 25,
    DELAY_INCREMENT: 40,
    INITIAL_DELAY: 200,
    SHUFFLE_DURATION: 500,
    SHUFFLE_DELAY_MS: 1350,
    FADE_DURATION_MS: 280,
  },
  MOUNT_BATCH_SIZE: 50,
} as const;
